services:
  db:
    image: postgres:16-alpine
    container_name: ev_pr01_awos
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
      - ./db/migrate.sql:/docker-entrypoint-initdb.d/03-migrate.sql
      - ./db/reports_vw.sql:/tmp/reports_vw.sql
      - ./db/indexes.sql:/tmp/indexes.sql
      - ./db/roles.sql:/tmp/roles.sql
      
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./api
    container_name: ev_pr01_api
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      PORT: 4000
    ports:
      - "4000:4000"

  web:
    build:
      context: ./web
    container_name: ev_pr01_web
    depends_on:
      - api
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    ports:
      - "3000:3000"

volumes:
  postgres_data: